application:
  subdomain: hakanai
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://hakanai:8080/
services:
  hakanai:
    #  ghcr.io/czerwonk/hakanai:v2.18.1
    # upstream: ghcr.io/czerwonk/hakanai:v3.0.8
    image: registry.lazycat.cloud/czyt/czerwonk/hakanai:8b8cdbc6e1f43c04
    environment:
      - HAKANAI_LISTEN_ADDRESS=0.0.0.0
      - HAKANAI_REDIS_DSN=redis://valkey:6379
    depends_on:
      - valkey
    binds:
      - /lzcapp/var/data:/data
  valkey:
    # valkey/valkey:alpine
    image: registry.lazycat.cloud/czyt/valkey/valkey:369af013ad4a641d
    healthcheck:
      test:
        - CMD-SHELL
        - sh -c echo PING | nc -w 5 localhost 6379 | grep PONG
      interval: 30s
