application:
  subdomain: hakanai
  background_task: true
  public_path:
    - /

  upstreams:
    - location: /
      backend: http://hakanai:8080/

services:
  hakanai:
    #  ghcr.io/czerwonk/hakanai:v2.18.1
    image: registry.lazycat.cloud/czyt/czerwonk/hakanai:cbee49e33f284dad
    environment:
      - HAKANAI_LISTEN_ADDRESS=0.0.0.0
      - HAKANAI_REDIS_DSN=redis://valkey:6379
    depends_on:
      - valkey
    binds:
      - /lzcapp/var/data:/data

  valkey:
    # valkey/valkey:alpine
    image: registry.lazycat.cloud/czyt/valkey/valkey:7207505b622b465d
    healthcheck:
      test:
        - CMD-SHELL
        - sh -c echo PING | nc -w 5 localhost 6379 | grep PONG
      interval: 30s
